Repository deepset-ai/FARM, pull requests merged in 2019-07, with the labels that each got.

#18 Add load_from_dir to Inferencer
  examples/doc_classification.py
  examples/embeddings_extraction.py
  examples/ner.py
  examples/question_answering.py
  farm/infer.py
  farm/modeling/prediction_head.py
  test/test_doc_classification.py
  test/test_ner.py
  test/test_question_answering.py
Labels: enhancement, help wanted

#22 fix issue #21 in custom_vocab with tokens that existed in original vocab
  farm/modeling/tokenization.py
Labels: bug

#20 Optional evals
  farm/data_handler/data_silo.py
  farm/train.py
Labels: enhancement
