Repository deepset-ai/FARM, pull requests merged in 2019-10, with the labels that each got.

#108 Add more tests & fix minor custom vocab bug
  farm/modeling/tokenization.py
  test/samples/tokenizer/bert-base-cased-vocab.txt
  test/samples/tokenizer/custom_vocab.txt
  test/test_processor_saving_loading.py
  test/test_tokenization.py
Labels: enhancement

#109 Windows fixes
  farm/__init__.py
  farm/data_handler/utils.py
Labels: bug

#106 Update transformers package to 2.0.0
  farm/data_handler/samples.py
  farm/modeling/language_model.py
  farm/modeling/prediction_head.py
  farm/modeling/tokenization.py
  requirements.txt
Labels: enhancement

#107 Add method to run inference from a file
  docs/examples.rst
  examples/doc_classification.py
  examples/doc_classification_multilabel.py
  examples/doc_regression.py
  examples/ner.py
  examples/question_answering.py
  farm/data_handler/data_silo.py
  farm/data_handler/processor.py
  farm/infer.py
  farm/inference_rest_api.py
  test/test_doc_classification.py
  test/test_doc_regression.py
  test/test_ner.py
  test/test_processor_saving_loading.py
  test/test_question_answering.py
Labels: enhancement

#121 Fix name of squad labels in experiment config
  experiments/qa/squad20_config.json
  farm/data_handler/processor.py
Labels: bug

#132 Fix passing kwargs to LM loading (e.g. proxy)
  farm/modeling/language_model.py
Labels: enhancement, part: model
