Repository deepset-ai/FARM, pull requests merged in 2019-12, with the labels that each got.

#165 Add early stopping and custom metrics
  examples/doc_classification_with_earlystopping.py
  farm/metrics.py
  farm/modeling/adaptive_model.py
  farm/modeling/language_model.py
  farm/train.py
Labels: enhancement, part: evaluator, part: trainer

#169 ALBERT Support
  examples/question_answering_debug.py
  farm/data_handler/input_features.py
  farm/data_handler/utils.py
  farm/modeling/adaptive_model.py
  farm/modeling/language_model.py
  farm/modeling/prediction_head.py
  farm/modeling/tokenization.py
  requirements.txt
Labels: part: model

#167 Issue59 - Add cross-validation for small datasets
  examples/doc_classification_crossvalidation.py
  farm/data_handler/data_silo.py
  farm/eval.py
  farm/train.py
Labels: enhancement

#175 Add train loss to tqdm. add desc for data preproc. log only 2 samples
  farm/data_handler/data_silo.py
  farm/data_handler/processor.py
  farm/train.py
Labels: enhancement

#174 WIP Add option to limit number of processes in datasilo
  examples/question_answering_debug.py
  farm/data_handler/data_silo.py
  farm/infer.py
  farm/inference_rest_api.py
  farm/utils.py
  test/test_inference.py
  test/test_ner.py
Labels: enhancement, part: data silo
