Repository deepset-ai/FARM, pull requests merged in 2019-08, with the labels that each got.

#31 fix accuracy metric for nested lists of diff lengths
  farm/metrics.py
  farm/utils.py
Labels: bug

#41 Fix use of list in batch_size config param (#38)
  farm/experiment.py
Labels: bug

#42 feat(logs): ascii art for easier + more pleasant visual inspection of logs
  farm/data_handler/data_silo.py
  farm/data_handler/processor.py
  farm/data_handler/samples.py
  farm/train.py
  farm/utils.py
  farm/visual/ascii/images.py
  farm/visual/ascii/text.py
Labels: enhancement

#43 Fix `output_dir` param in configs (#39)
  experiments/lm_finetuning/finetune_sample_config.json
  experiments/ner/conll2003_de_config.json
  experiments/ner/germEval14_config.json
  experiments/qa/squad20_config.json
  experiments/text_classification/germEval18Coarse_config.json
  experiments/text_classification/germEval18Fine_config.json
  experiments/text_classification/gnad_config.json
  farm/data_handler/processor.py
  farm/experiment.py
  farm/file_utils.py
  farm/modeling/adaptive_model.py
Labels: bug

#44 fix(lm_finetuning): add sample data to run example script
  examples/lm_finetuning.py
  farm/data_handler/processor.py
  farm/data_handler/samples.py
  farm/data_handler/utils.py
Labels: bug

#52 docs: add sketches. move images to own folder. fix docstrings.
  docs/basic_usage.rst
  docs/conf.py
  docs/data_handling.rst
  docs/img/adaptive_model_no_bg.jpg
  docs/img/code_snippet_building_blocks.png
  docs/img/code_snippet_experiment.png
  docs/img/data_silo_no_bg.jpg
  docs/img/inference-api-screen.png
  docs/img/logo.png
  docs/img/logo_with_name.png
  docs/img/sample_basket_no_bg.jpg
  docs/installation.rst
  docs/modeling.rst
  farm/infer.py
  readme.rst
Labels: documentation

#54 Fix lr schedule
  examples/doc_classification.py
  examples/lm_finetuning.py
  examples/ner.py
  examples/question_answering.py
  farm/experiment.py
  farm/modeling/optimization.py
  test/test_doc_classification.py
  test/test_ner.py
  test/test_question_answering.py
  tutorials/1_farm_building_blocks.ipynb
Labels: bug

#55 Add whole word masking
  examples/lm_finetuning.py
  farm/data_handler/input_features.py
  farm/data_handler/processor.py
  farm/data_handler/samples.py
  farm/data_handler/utils.py
  farm/modeling/adaptive_model.py
  test/samples/lm_finetuning/test-sample.txt
  test/samples/lm_finetuning/train-sample.txt
  test/test_lm_finetuning.py
Labels: enhancement

#56 Add logging of params (batch_size, lm name)
  farm/data_handler/data_silo.py
  farm/modeling/adaptive_model.py
  farm/modeling/language_model.py
Labels: enhancement

#61 Refactor eval to reduce memory footprint
  farm/eval.py
Labels: enhancement

#58 Add multi-gpu support for "building blocks" mode
  examples/lm_finetuning.py
  examples/question_answering.py
  farm/experiment.py
  farm/train.py
  test/test_lm_finetuning.py
  test/test_question_answering.py
Labels: enhancement

#62 Merge Processors, adjust config to be nested
  docs/basic_usage.rst
  examples/doc_classification.py
  examples/embeddings_extraction.py
  examples/ner.py
  experiments/lm_finetuning/finetune_sample_config.json
  experiments/ner/conll2003_de_config.json
  experiments/ner/germEval14_config.json
  experiments/qa/squad20_config.json
  experiments/text_classification/germEval18Coarse_config.json
  experiments/text_classification/germEval18Fine_config.json
  experiments/text_classification/gnad_config.json
  farm/data_handler/processor.py
  farm/experiment.py
  farm/file_utils.py
  run_all_experiments.py
  test/test_doc_classification.py
  test/test_lm_finetuning.py
  test/test_ner.py
  tutorials/1_farm_building_blocks.ipynb
Labels: enhancement

#65 Update screenshot of UI
  docs/img/inference-api-screen.png
Labels: documentation

#50 Add prediction head for regression
  examples/doc_regression.py
  farm/data_handler/processor.py
  farm/eval.py
  farm/metrics.py
  farm/modeling/adaptive_model.py
  farm/modeling/prediction_head.py
  test/samples/doc_regr/test-sample.tsv
  test/samples/doc_regr/train-sample.tsv
  test/test_doc_regression.py
Labels: enhancement

#69 Add user friendly error message for wrong doc input format
  farm/data_handler/utils.py
Labels: documentation

#72 Add InferenceProcessor
  examples/embeddings_extraction.py
  farm/data_handler/input_features.py
  farm/data_handler/processor.py
  farm/infer.py
  farm/modeling/language_model.py
  requirements.txt
  test/test_lm_finetuning.py
Labels: enhancement

#74 Parse labels to float in regression processor
  examples/doc_regression.py
  farm/data_handler/processor.py
Labels: bug

#73 Add max number of docs to read from file
  examples/lm_finetuning.py
  farm/data_handler/processor.py
  farm/data_handler/utils.py
Labels: enhancement
