Repository deepset-ai/FARM, pull requests merged in 2020-06, with the labels that each got.

#305 Speed optimization training from scratch
  Dockerfile-GPU
  Dockerfile-SageMaker
  examples/train_from_scratch.py
  examples/train_from_scratch_with_sagemaker.py
  farm/data_handler/data_silo.py
  farm/data_handler/processor.py
  farm/data_handler/utils.py
  farm/eval.py
  farm/modeling/optimization.py
  farm/train.py
  farm/utils.py
Labels: enhancement, part: model, part: trainer

#437 Conditional num_training_steps setting
  farm/modeling/optimization.py
  test/modeling/test_optimization.py
Labels: enhancement, part: optimizer

#427 Fix util for randomisation of train file
  examples/train_from_scratch.py
  examples/train_from_scratch_with_sagemaker.py
  farm/data_handler/utils.py
Labels: bug
