Repository deepset-ai/FARM, pull requests merged in 2020-04, with the labels that each got.

#331 Registration and parametrization for evaluation reports
  farm/eval.py
  farm/evaluation/metrics.py
  farm/train.py
Labels: enhancement, part: evaluator

#285 Add glove, word2vec and fasttext as Language Model
  examples/doc_classification_fasttext_LM.py
  examples/doc_classification_word_embedding_LM.py
  examples/wordembedding_inference.py
  farm/data_handler/data_silo.py
  farm/data_handler/processor.py
  farm/file_utils.py
  farm/modeling/language_model.py
  farm/modeling/tokenization.py
  farm/modeling/wordembedding_utils.py
Labels: enhancement, part: model

#286 S3E pooling of embeddings
  examples/embeddings_extraction_s3e_pooling.py
  farm/data_handler/data_silo.py
  farm/data_handler/processor.py
  farm/infer.py
  farm/modeling/language_model.py
  farm/modeling/tokenization.py
  farm/modeling/wordembedding_utils.py
  farm/utils.py
  test/samples/s3e/fitted_s3e/language_model_config.json
  test/samples/s3e/fitted_s3e/processor_config.json
  test/samples/s3e/fitted_s3e/s3e_stats.pkl
  test/samples/s3e/fitted_s3e/vectors.txt
  test/samples/s3e/fitted_s3e/vocab.txt
  test/samples/s3e/tiny_corpus.txt
  test/samples/s3e/tiny_fasttext_model/language_model_config.json
  test/samples/s3e/tiny_fasttext_model/vectors.txt
  test/samples/s3e/tiny_fasttext_model/vocab.txt
  test/test_s3e_pooling.py
Labels: enhancement, part: inference
